version: '3'
services:
  db:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin123!
    ports:
      - 1433:1433
    volumes:
      - sqlserver:/var/opt/mssql  
  
  microservice:
    ports:
      - 8080:8080
    build:
      context: .
      args:
        JAR_FILE: target/sample-springboot-mssql-server-0.0.1-SNAPSHOT.jar
    depends_on:
      - db
    links:
      - db
      
volumes:
  sqlserver:
